idf_component_register(SRCS "recive.c"
                       INCLUDE_DIRS "."
                                    "hardware"
                                    "hardware/drivers"
                                    "hardware/peripherals"
                                    "middleware"
                                    "service"
                                    "components")
